
default: &default
  adapter: postgresql
  encoding: unicode
  database: recycling_radar
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: recycling_radar_development


test:
  <<: *default
  database: recycling_radar_test